### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by jhoblitt** [voxpupuli/puppet-tuned#2]
There isn't any gha configuration in the repo.

**Comment by jcpunk** [comment]
In theory I may have setup some sort of CI for a PR....

**Comment by jhoblitt** [comment]
There's always modsync...

**Comment by jcpunk** [comment]
Sadly I can never seem to get ruby applications to run on any of my systems... Somehow I've always got a version that is too old or too new.

I'd be totally willing to donate this to Vox if you think it would be useful there.

**Comment by jhoblitt** [comment]
For ruby version switching, I use https://rvm.io/. There is also https://github.com/rbenv/rbenv (and probably others).

I would be completely willing to do the modulesync work if you want to donate in to vox.

**Comment by jcpunk** [comment]
https://github.com/voxpupuli/modulesync_config/pull/847  Donated

**Comment by jhoblitt** [comment]
Thanks for adding more work to my pile ;)
